name: Broadcast
version: ${project.version}
main: me.rocket.broadcast.Broadcast
api-version: 1.13
authors: [your, mother]
description: broadcast in 30 seconds or less with your mom
commands:
  broadcast:
    description: Broadcast your feelings to people who don't care.
    aliases: [bc]
  home:
    description: Go back to your home where no one waits.
  fly:
    description: Fly away from your problems.
    aliases: [flight]
  tp:
    description: Teleport away from your problems.
    aliases: [teleport]
  pm:
    description: Send your thoughts to someone who won't care.
    aliases: [msg, dm]
  heal:
    description: Heal your physical pain, not your mental pain.
  feed:
    description: Feed your pain away.